import {z} from 'zod';
import {db,access,writeRoles,adminRoles,origin,rate,readJSON,now,id,fail,ApiError,auditStmt,safeUrl} from '@/lib/crm';
import {integrationEnv,gmailConfigured,gmail,mime} from '@/lib/gmail';
import {draftFor,verified,verificationStates,validEmail,normalize,businessDate} from '@/lib/prospecting';
const reply=(d:any,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'no-store'}});
const error=(e:any)=>reply({error:e instanceof ApiError?e.message:e instanceof z.ZodError?e.issues[0].message:'Research action failed. Please try again.'},e instanceof ApiError?e.status:e instanceof z.ZodError?400:500);
async function record(t:string,rid:string){const r=await db().prepare("SELECT * FROM records WHERE tenant=? AND id=? AND kind='research'").bind(t,rid).first<any>();if(!r)fail('Research record not found.',404);return {...r,data:JSON.parse(r.data)};}
async function save(t:string,rid:string,d:any){await db().prepare('UPDATE records SET data=?,updated=? WHERE tenant=? AND id=?').bind(JSON.stringify(d),now(),t,rid).run();}
const editable=z.object({organization:z.string().trim().min(1).max(250),lead_type:z.enum(['Schools','NGOs']),contact_person:z.string().max(200).default(''),designation:z.string().max(150).default(''),email:z.string().max(254).default(''),alternate_email:z.string().max(254).default(''),phone:z.string().max(60).default(''),website:z.string().max(2000).default(''),city:z.string().max(150).default(''),district:z.string().max(150).default(''),state:z.string().max(150).default(''),country:z.string().max(100).default('India'),address:z.string().max(1000).default(''),board:z.string().max(150).default(''),focus_area:z.string().max(500).default(''),beneficiaries:z.string().max(500).default(''),verification:z.enum(verificationStates),evidence_url:z.string().max(2000).default(''),email_evidence:z.string().max(2000).default(''),personalization_notes:z.string().max(3000).default(''),confidence:z.number().min(0).max(100).default(0),score:z.number().min(0).max(100).default(0),priority:z.enum(['Low','Medium','High']).default('Medium'),do_not_contact:z.boolean().default(false),consent:z.boolean().default(false),consent_evidence:z.string().max(1000).default(''),internal_notes:z.string().max(3000).default('')});
export async function GET(req:Request){try{const t=new URL(req.url).searchParams.get('tenant')||'';const {m}=await access(t,writeRoles);const rows=await db().prepare("SELECT * FROM records WHERE tenant=? AND kind IN ('research','research_run') ORDER BY created DESC LIMIT 5000").bind(t).all<any>();const connection=await db().prepare("SELECT updated FROM integrations WHERE tenant=? AND provider='gmail'").bind(t).first();return reply({records:rows.results.map(r=>({...r,data:JSON.parse(r.data)})),admin:adminRoles.includes(m.role),searchConfigured:!!integrationEnv.BRAVE_SEARCH_API_KEY,gmailConfigured:gmailConfigured(),gmailConnected:!!connection});}catch(e){return error(e);}}
export async function POST(req:Request){try{origin(req);const d=await readJSON(req,100000);const t=z.string().uuid().parse(d.tenant);const {u,m,config:c,b}=await access(t,writeRoles);if(!JSON.parse(b.modules).includes('leads'))fail('Lead module is disabled.',403);await rate('research:'+u.userId,40);const admin=()=>{if(!adminRoles.includes(m.role))fail('Administrator approval required.',403);};
 if(d.op==='search'){
  if(!integrationEnv.BRAVE_SEARCH_API_KEY)fail('Public search is not connected. Configure BRAVE_SEARCH_API_KEY in the hosting secrets.',409);
  await rate('research-search:'+t,6);
  const input=z.object({city:z.string().trim().min(2).max(100),district:z.string().max(100).default(''),state:z.string().max(100).default(''),country:z.string().max(100).default('India'),target:z.enum(['Schools','NGOs','Both']),filter:z.string().max(150).default(''),page:z.number().int().min(0).max(9).default(0)}).parse(d);
  const location=[input.city,input.district,input.state,input.country].filter(Boolean).join(' ');const types=input.target==='Both'?['Schools','NGOs']:[input.target];let added=0,duplicates=0;const errors:string[]=[];
  for(const type of types){const query=`${location} ${type==='Schools'?'school official contact affiliation':'NGO foundation education official contact'} ${input.filter}`;const url=new URL('https://api.search.brave.com/res/v1/web/search');url.search=new URLSearchParams({q:query,count:'20',offset:String(input.page),extra_snippets:'true'}).toString();const response=await fetch(url,{headers:{'X-Subscription-Token':integrationEnv.BRAVE_SEARCH_API_KEY!,Accept:'application/json'},signal:AbortSignal.timeout(20000)});if(!response.ok){errors.push(type+': search provider could not complete the request');continue;}const result:any=await response.json();
   for(const hit of result.web?.results||[]){const source=safeUrl(hit.url);const fingerprint=source.replace(/\/$/,'');const old=await db().prepare("SELECT id FROM records WHERE tenant=? AND kind='research' AND json_extract(data,'$.source_url')=?").bind(t,source).first();if(old){duplicates++;continue;}const clean=(s:string)=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').slice(0,4000);const excerpt=clean([hit.description,...(hit.extra_snippets||[])].join(' '));const emails=Array.from(new Set(excerpt.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[]));const rid=id();const item={organization:clean(hit.title),lead_type:type,email:emails[0]||'',alternate_email:emails[1]||'',source_url:source,source_type:'Public search result',source_excerpt:excerpt,search_location:location,city:input.city,district:input.district,state:input.state,country:input.country,verification:emails.length?'Needs manual review':'Email not found',score:0,confidence:0,priority:'Low',stage:'Researched',draft_status:'Not created',do_not_contact:false,consent:false,personalization_notes:'',fingerprint};const insert=await db().prepare("INSERT OR IGNORE INTO records (id,tenant,kind,data,email,created,updated) VALUES (?,?,'research',?,?,?,?)").bind(rid,t,JSON.stringify(item),fingerprint,now(),now()).run();if(insert.meta.changes)added++;else duplicates++;}
  }
  const run={...input,added,duplicates,errors,completed_at:now()};await db().batch([db().prepare("INSERT INTO records (id,tenant,kind,data,created,updated) VALUES (?,?,'research_run',?,?,?)").bind(id(),t,JSON.stringify(run),now(),now()),auditStmt(t,u.email,`Research: ${added} source candidates, ${duplicates} duplicate sources skipped`)]);return reply({...run,message:'Search results are candidates, not verified organizations. Review original sources before drafting. Load the next page to discover more.'});
 }
 if(d.op==='disconnect'){admin();await db().batch([db().prepare("DELETE FROM integrations WHERE tenant=? AND provider='gmail'").bind(t),auditStmt(t,u.email,'Gmail disconnected')]);return reply({ok:true});}
 const rid=z.string().uuid().parse(d.id);const rec=await record(t,rid);let r=rec.data;
 if(d.op==='review'){
  if(['Creating','Sending','Sent','Needs delivery review'].includes(r.draft_status))fail('This record is locked to preserve its email history.');const input=editable.parse(d.data);if(input.email&&!validEmail(input.email))fail('Enter a valid email or leave it empty.');input.website=safeUrl(input.website);input.evidence_url=safeUrl(input.evidence_url);if(verified(input.verification)&&(!input.evidence_url||!input.email_evidence||!input.personalization_notes||!validEmail(input.email)))fail('Verified leads require an email, source URL, contact evidence and a verified personalization fact.');if(input.consent&&!input.consent_evidence)fail('Record the actual consent evidence. Public contact details do not imply consent.');
  const others=(await db().prepare("SELECT id,data FROM records WHERE tenant=? AND id!=? AND kind IN ('lead','research')").bind(t,rid).all<any>()).results;const dup=others.find(x=>{const v=JSON.parse(x.data);return (input.email&&v.email?.toLowerCase()===input.email.toLowerCase())||(input.phone&&normalize(input.phone).length>6&&normalize(input.phone)===normalize(v.phone))||(input.website&&input.website===v.website)||(normalize(input.organization).length>4&&normalize(input.organization)===normalize(v.organization||v.company)&&normalize(input.city)===normalize(v.city));});r={...r,...input,email:input.email.toLowerCase(),duplicate_of:dup?.id||null,reviewed_at:now(),reviewed_by:u.email,date_verified:verified(input.verification)?now():null,draft_status:r.gmail_draft_id?'Draft needs update':'Not created',stage:verified(input.verification)?'Verified':'Researched'};await save(t,rid,r);await db().prepare("UPDATE sends SET status='draft',approved_by=NULL WHERE tenant=? AND lead=? AND status='approved'").bind(t,rid).run();await auditStmt(t,u.email,'Research record reviewed',rid).run();return reply({ok:true,duplicate:!!dup});
 }
 if(d.op==='personalize'){if(r.duplicate_of||r.do_not_contact||r.unsubscribed)fail('Duplicate or suppressed records cannot be drafted.');if(['Creating','Sending','Sent','Needs delivery review'].includes(r.draft_status))fail('This record is locked.');const draft=draftFor(r,c);r={...r,...draft,draft_status:'Pending review',stage:'Draft Created',approved_by:null};await save(t,rid,r);await auditStmt(t,u.email,'Personalized preview generated',rid).run();return reply({ok:true});}
 if(d.op==='edit-draft'){if(!r.subject||['Creating','Sending','Sent','Needs delivery review'].includes(r.draft_status))fail('Draft cannot be edited now.');r={...r,subject:z.string().trim().min(1).max(300).refine(v=>!/[\r\n]/.test(v)).parse(d.subject),body:z.string().trim().min(1).max(15000).parse(d.body),draft_status:'Pending review',approved_by:null};await save(t,rid,r);await db().prepare("UPDATE sends SET status='draft',approved_by=NULL WHERE tenant=? AND lead=? AND status='approved'").bind(t,rid).run();return reply({ok:true});}
 if(!JSON.parse(b.modules).includes('outreach'))fail('Outreach module is disabled.',403);
 if(d.op==='gmail-draft'){
  if(!verified(r.verification)||!validEmail(r.email)||!r.subject||!r.body||r.duplicate_of||r.do_not_contact||r.unsubscribed)fail('Review and personalize a verified lead first.');
  if(!gmailConfigured())fail('Gmail OAuth is not configured.',409);if(['Creating','Sending','Sent','Needs delivery review'].includes(r.draft_status))fail('Draft operation is locked. Check Gmail before retrying.');
  const connection=await db().prepare("SELECT tenant FROM integrations WHERE tenant=? AND provider='gmail'").bind(t).first();if(!connection)fail('Connect Gmail before creating drafts.',409);const claimProvider='draft:'+r.email.toLowerCase();await db().prepare("INSERT OR IGNORE INTO integrations (tenant,provider,data,updated) VALUES (?,?,?,?)").bind(t,claimProvider,rid,now()).run();const claim=await db().prepare("SELECT data FROM integrations WHERE tenant=? AND provider=?").bind(t,claimProvider).first<any>();if(claim.data!==rid)fail('A Gmail draft for this recipient already exists in this business.');
  const lock=await db().prepare("UPDATE records SET data=json_set(data,'$.draft_status','Creating'),updated=? WHERE tenant=? AND id=? AND updated=?").bind(now(),t,rid,rec.updated).run();if(!lock.meta.changes)fail('Record changed. Refresh before retrying.',409);
  const token=r.unsubscribe_token||id()+id();const unsubscribe=new URL('/unsubscribe?token='+token,req.url).href;const sendBody=r.body+'\n\nUnsubscribe: '+unsubscribe;try{const result=await gmail(t,r.gmail_draft_id?'drafts/'+encodeURIComponent(r.gmail_draft_id):'drafts',r.gmail_draft_id?'PUT':'POST',{message:{raw:mime(r.email,r.subject,sendBody,rid)}});r={...r,gmail_draft_id:result.id,gmail_message_id:result.message?.id,unsubscribe_token:token,send_body:sendBody,draft_status:'Draft created',stage:'Pending Approval',approved_by:null,draft_created_at:r.draft_created_at||now()};await db().prepare("INSERT INTO sends (id,tenant,lead,campaign,subject,body,status,token,created,updated,attachments) VALUES (?,?,?,?,?,?,'draft',?,?,?,'[]') ON CONFLICT(tenant,lead,campaign) DO UPDATE SET subject=excluded.subject,body=excluded.body,status='draft',approved_by=NULL,updated=excluded.updated").bind(id(),t,rid,'research-gmail',r.subject,r.body,token,now(),now()).run();await save(t,rid,r);await auditStmt(t,u.email,'Gmail draft created or updated',rid).run();return reply({ok:true,gmail_draft_id:result.id});}catch(e){await save(t,rid,{...r,draft_status:'Needs delivery review'});throw e;}
 }
 if(d.op==='approve'){admin();if(d.previewed!==true||r.draft_status!=='Draft created'||!r.gmail_draft_id||r.do_not_contact||r.unsubscribed)fail('Review a current Gmail draft before approval.');r={...r,draft_status:'Approved',approved_by:u.email,approved_at:now(),stage:'Approved'};await save(t,rid,r);await db().prepare("UPDATE sends SET status='approved',approved_by=?,updated=? WHERE tenant=? AND lead=? AND campaign='research-gmail' AND status='draft'").bind(u.email,now(),t,rid).run();await auditStmt(t,u.email,'Gmail draft approved',rid).run();return reply({ok:true});}
 if(d.op==='send'){admin();if(d.previewed!==true||d.confirm_send!==true||r.draft_status!=='Approved'||!r.approved_by||!r.gmail_draft_id)fail('Explicit approval of this preview is required.');if(!r.consent||!r.consent_evidence||r.do_not_contact||r.unsubscribed||r.duplicate_of||r.response_status==='Replied')fail('Recipient is suppressed or outreach consent is missing.');await rate('gmail-send:'+t,5);
  const count=await db().prepare("SELECT COUNT(*) AS total FROM sends WHERE tenant=? AND status IN ('sent','delivered','sending') AND updated>=?").bind(t,new Date().toISOString().slice(0,10)).first<any>();if(count.total>=Number(c.daily_sending_limit||25))fail('Daily sending limit reached.',429);
  const sent=await db().prepare("SELECT id FROM sends WHERE tenant=? AND lead=? AND campaign='research-gmail' AND status='approved'").bind(t,rid).first<any>();if(!sent)fail('The message is no longer approved.');const lock=await db().prepare("UPDATE sends SET status='sending',updated=? WHERE id=? AND tenant=? AND status='approved'").bind(now(),sent.id,t).run();if(!lock.meta.changes)fail('Send already in progress.',409);await save(t,rid,{...r,draft_status:'Sending'});
  try{const draft=await gmail(t,'drafts/'+encodeURIComponent(r.gmail_draft_id)+'?format=full');const payload=draft.message?.payload;const headers=payload?.headers||[];const h=(n:string)=>headers.find((x:any)=>x.name.toLowerCase()===n)?.value;const decode=(v:string)=>{const s=v.replace(/-/g,'+').replace(/_/g,'/');return new TextDecoder().decode(Uint8Array.from(atob(s),x=>x.charCodeAt(0)));};if(h('to')!==r.email||h('subject')!==r.subject||!payload?.body?.data||decode(payload.body.data).trim()!==r.send_body.trim())fail('The Gmail draft changed outside CRM. Update and review it again.',409);const result=await gmail(t,'drafts/send','POST',{id:r.gmail_draft_id});r={...r,draft_status:'Sent',stage:'Sent',gmail_message_id:result.id,last_contacted_at:now(),next_follow_up:businessDate(now(),Number(c.follow_up_rules?.[0]||5))};await save(t,rid,r);await db().batch([db().prepare("UPDATE sends SET status='sent',provider=?,updated=? WHERE id=? AND tenant=?").bind(result.id,now(),sent.id,t),auditStmt(t,u.email,'Approved Gmail email sent',rid),db().prepare("INSERT INTO records (id,tenant,kind,data,created,updated) VALUES (?,?,'task',?,?,?)").bind(id(),t,JSON.stringify({title:'Follow up: '+r.organization,body:'Check for replies before preparing the next message.',status:'Open',lead:rid,due:r.next_follow_up,assigned_to:u.email}),now(),now())]);return reply({ok:true});}catch(e){await save(t,rid,{...r,draft_status:'Needs delivery review'});await db().prepare("UPDATE sends SET status='review_required',updated=? WHERE tenant=? AND id=?").bind(now(),t,sent.id).run();throw e;}
 }
 if(d.op==='suppress'){r={...r,do_not_contact:true,next_follow_up:'',stage:'Do Not Contact'};await save(t,rid,r);await db().prepare("UPDATE records SET data=json_set(data,'$.status','Complete'),updated=? WHERE tenant=? AND kind='task' AND json_extract(data,'$.lead')=?").bind(now(),t,rid).run();await auditStmt(t,u.email,'Do not contact; follow-ups stopped',rid).run();return reply({ok:true});}
 if(d.op==='replied'){r={...r,response_status:'Replied',next_follow_up:'',stage:'Replied'};await save(t,rid,r);await db().prepare("UPDATE records SET data=json_set(data,'$.status','Complete'),updated=? WHERE tenant=? AND kind='task' AND json_extract(data,'$.lead')=?").bind(now(),t,rid).run();await auditStmt(t,u.email,'Reply recorded; follow-ups stopped',rid).run();return reply({ok:true});}
 return fail('Unknown research action.');
 }catch(e){return error(e);}}
