'use client';
import {useEffect,useState} from 'react';
import {Search,MapPin,CheckCircle2,Mail,ExternalLink,Download,X,ShieldCheck} from 'lucide-react';
import {verificationStates,verified} from '@/lib/prospecting';
import {exportResearch} from '@/lib/research-export';
export default function Research({tenant,config,onChange}:{tenant:string;config:any;onChange:()=>void}){
 const [data,D]=useState<any>(null),[busy,B]=useState(false),[error,E]=useState(''),[notice,N]=useState(''),[form,F]=useState({city:'',district:'',state:'',country:'India',target:'Schools',filter:'',page:0}),[selection,S]=useState<string[]>([]),[filter,Q]=useState(''),[onlyVerified,OV]=useState(false),[modal,M]=useState<any>(null),[edit,U]=useState<any>({}),[page,P]=useState(1);
 async function load(){try{const res=await fetch('/api/research?tenant='+tenant);const d:any=await res.json();if(!res.ok)throw Error(d.error);D(d);}catch(e:any){E(e.message);}}
 useEffect(()=>{load();},[tenant]);
 async function action(payload:any){B(true);E('');try{const res=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenant,...payload})});const d:any=await res.json();if(!res.ok)throw Error(d.error);await load();onChange();return d;}catch(e:any){E(e.message);return null;}finally{B(false);}}
 const dirty=modal?.type==='preview'&&(edit.subject!==modal.r.data.subject||edit.body!==modal.r.data.body);
 const leads=(data?.records||[]).filter((x:any)=>x.kind==='research');const runs=(data?.records||[]).filter((x:any)=>x.kind==='research_run');const shown=leads.filter((x:any)=>(!onlyVerified||verified(x.data.verification))&&[x.data.organization,x.data.email,x.data.city,x.data.lead_type].join(' ').toLowerCase().includes(filter.toLowerCase()));
 const metrics=[['Source candidates',leads.length],['Verified',leads.filter((x:any)=>verified(x.data.verification)).length],['Without email',leads.filter((x:any)=>!x.data.email).length],['Duplicate sources skipped',runs.reduce((s:number,x:any)=>s+(x.data.duplicates||0),0)],['Gmail drafts',leads.filter((x:any)=>x.data.gmail_draft_id).length],['Sent',leads.filter((x:any)=>x.data.draft_status==='Sent').length],['Replies recorded',leads.filter((x:any)=>x.data.response_status==='Replied').length],['Follow-ups due',leads.filter((x:any)=>x.data.next_follow_up&&x.data.next_follow_up<=new Date().toISOString().slice(0,10)&&!x.data.unsubscribed&&!x.data.do_not_contact).length]];
 function open(r:any,type:string){M({r,type});U({...r.data});}
 async function selectedDrafts(){let success=0;for(const rid of selection){const r=await action({op:'gmail-draft',id:rid});if(!r)break;success++;}N(`${success} Gmail drafts saved. Nothing was sent.`);S([]);}
 function exportJSON(){const rows=leads.filter((x:any)=>!selection.length||selection.includes(x.id)).map((x:any)=>({lead_id:x.id,...x.data}));const blob=new Blob([JSON.stringify(rows,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='research-leads.json';a.click();URL.revokeObjectURL(url);}
 if(!data)return <section className="card research-panel"><h2>Opening lead research…</h2>{error&&<p role="alert">{error}</p>}</section>;
 return <div className="research-workspace">
  <div className="research-steps">{['Research','Verify','Review','Personalize','Create drafts','Approve','Send'].map((s,i)=><span key={s}><b>{i+1}</b>{s}</span>)}</div>
  {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="success" role="status">{notice}</div>}
  <section className="card research-panel"><div className="research-title"><div><span className="eyebrow">PUBLIC SOURCE RESEARCH</span><h2>Find your next school or NGO partner</h2><p>Choose a location. Review evidence before creating outreach.</p></div><span className="badge"><ShieldCheck size={14}/>Draft only by default</span></div>
   <form onSubmit={async e=>{e.preventDefault();const r=await action({op:'search',...form,page:0});if(r){F({...form,page:0});N(`${r.added} source candidates found · ${r.duplicates} duplicate sources skipped. ${r.message}`);}}}>
    <div className="research-form"><label>City or region<input required minLength={2} maxLength={100} value={form.city} onChange={e=>F({...form,city:e.target.value})} placeholder="Enter any city or district"/></label><label>Target type<select value={form.target} onChange={e=>F({...form,target:e.target.value})}>{['Schools','NGOs','Both'].map(x=><option key={x}>{x}</option>)}</select></label><button className="primary" disabled={busy||!data.searchConfigured}><Search size={16}/>{busy?'Working…':'Find leads'}</button></div>
    <details><summary>Location and search filters</summary><div className="form-grid"><label>District<input value={form.district} onChange={e=>F({...form,district:e.target.value})}/></label><label>State<input value={form.state} onChange={e=>F({...form,state:e.target.value})}/></label><label>Country<input value={form.country} onChange={e=>F({...form,country:e.target.value})}/></label><label>Board or focus<select value={form.filter} onChange={e=>F({...form,filter:e.target.value})}>{['','CBSE','ICSE','ISC','State Board','Government','Private','Residential','Senior Secondary','Education NGO','STEM NGO','Girls education','Rural education','CSR Foundation'].map(x=><option key={x} value={x}>{x||'All'}</option>)}</select></label></div><p>Search covers the entered region. A geographic radius is not applied. Results can include directories; each organization and contact needs source review.</p></details>
   </form>
   <div className="connection-row"><span className={data.searchConfigured?'badge verified':'badge'}>Public search: {data.searchConfigured?'connected':'setup required'}</span><span className={data.gmailConnected?'badge verified':'badge'}>Gmail: {data.gmailConnected?'connected':'not connected'}</span>{data.admin&&data.gmailConfigured&&!data.gmailConnected&&<a className="button" href={'/api/gmail?tenant='+tenant}>Connect Gmail</a>}{data.admin&&data.gmailConnected&&<button disabled={busy} onClick={()=>action({op:'disconnect'})}>Disconnect Gmail</button>}</div>
   {(!data.searchConfigured||!data.gmailConfigured)&&<details className="integration-help"><summary>Connection setup required</summary><p>The platform owner configures a Brave Search API key, Google OAuth client and encryption key in hosting secrets. Then a business admin selects Connect Gmail once. Browser Gmail login alone does not connect this app.</p><p>Google callback: <code>/api/gmail</code> on this site's HTTPS domain. Private credentials never belong in a lead or business form.</p></details>}
  </section>
  <div className="research-metrics">{metrics.map(([label,value])=><div className="card" key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div>
  <section className="card"><div className="card-head"><div><h2>Research review</h2><p>Verified means reviewed against the cited source; it does not confirm inbox deliverability.</p></div><div className="connection-row">{['csv','xlsx','pdf','json'].map(format=><button key={format} disabled={busy} onClick={async()=>{B(true);try{await exportResearch(leads.filter((x:any)=>!selection.length||selection.includes(x.id)),format);}catch(e:any){E(e.message);}finally{B(false);}}}><Download size={15}/>{format.toUpperCase()}</button>)}</div></div><div className="research-toolbar"><input aria-label="Search research leads" placeholder="Search organizations, location or email" value={filter} onChange={e=>{Q(e.target.value);P(1);}}/><label className="check"><input type="checkbox" checked={onlyVerified} onChange={e=>{OV(e.target.checked);P(1);}}/>Verified only</label><button onClick={()=>S(shown.filter((x:any)=>verified(x.data.verification)&&x.data.email&&!x.data.duplicate_of&&!x.data.do_not_contact&&!x.data.unsubscribed).map((x:any)=>x.id))}>Select verified</button><button disabled={busy||!selection.length||!data.gmailConnected} onClick={selectedDrafts}>Create {selection.length||''} Gmail drafts</button></div>
   {shown.length?<div className="table-wrap"><table><thead><tr>{['Select','Organization / location','Email','Type','Verification','Score','Draft status','Source','Review'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{shown.slice((page-1)*15,page*15).map((x:any)=>{const r=x.data;return <tr key={x.id}><td><input type="checkbox" aria-label={'Select '+r.organization} checked={selection.includes(x.id)} onChange={e=>S(e.target.checked?[...selection,x.id]:selection.filter(v=>v!==x.id))}/></td><td><strong>{r.organization}</strong><small className="cell-small">{[r.city,r.state].filter(Boolean).join(', ')}</small></td><td>{r.email||'Email not found'}</td><td>{r.lead_type}</td><td><span className="badge">{r.duplicate_of?'Duplicate':r.verification}</span></td><td>{r.score||0}<small className="cell-small">{r.priority||'Low'}</small></td><td>{r.draft_status||'Not created'}</td><td><a href={r.source_url} target="_blank" rel="noreferrer">Source <ExternalLink size={12}/></a></td><td><button onClick={()=>open(x,'review')}>Review</button>{r.subject&&<button onClick={()=>open(x,'preview')}>Preview</button>}</td></tr>;})}</tbody></table></div>:<div className="empty"><MapPin size={28}/><h3>Your location is the starting point</h3><p>Search public sources to build a reviewable list. No sample organizations are added automatically.</p></div>}
   <div className="pagination"><span>{shown.length} source candidates · page {page}</span><button disabled={page<=1} onClick={()=>P(page-1)}>Previous</button><button disabled={page*15>=shown.length} onClick={()=>P(page+1)}>Next</button><button disabled={busy||!data.searchConfigured||!form.city||form.page>=9} onClick={async()=>{const next=form.page+1;const r=await action({op:'search',...form,page:next});if(r){F({...form,page:next});N(`${r.added} additional candidates; ${r.duplicates} duplicates skipped.`);}}}>Research next source page</button></div><p className="research-footnote">There is no fixed 20-lead total. Source pages are researched in batches. Search coverage is not an exhaustive registry of every organization.</p>
  </section>
  {modal&&<div className="modal-backdrop"><section className="modal research-modal" role="dialog" aria-modal="true" aria-label={modal.type==='review'?'Review research evidence':'Personalized email preview'}><div className="modal-head"><h2>{modal.type==='review'?'Review research evidence':'Personalized email preview'}</h2><button aria-label="Close research dialog" onClick={()=>M(null)}><X size={18}/></button></div>{modal.type==='review'?<>
   <div className="info"><a href={edit.source_url} target="_blank" rel="noreferrer">Open original source <ExternalLink size={14}/></a><p>{edit.source_excerpt}</p></div><p className="research-footnote">A search title may name a directory or contain multiple institutions. Confirm the organization and location before saving.</p>
   <form onSubmit={async e=>{e.preventDefault();const r=await action({op:'review',id:modal.r.id,data:{...edit,confidence:Number(edit.confidence||0),score:Number(edit.score||0),do_not_contact:!!edit.do_not_contact,consent:!!edit.consent}});if(r){M(null);N(r.duplicate?'Saved; possible duplicate excluded from drafts.':'Evidence review saved.');}}}><div className="form-grid">
    {['organization','contact_person','designation','email','alternate_email','phone','website','city','district','state','country','address','board','focus_area','beneficiaries','evidence_url','email_evidence','personalization_notes','internal_notes','consent_evidence'].map(k=><label key={k}>{({organization:'Organization name',evidence_url:'Verification source URL',email_evidence:'Exact source evidence for email',personalization_notes:'Verified organization-specific fact',consent_evidence:'Consent evidence (if granted)'} as any)[k]||k.replaceAll('_',' ')}{['personalization_notes','internal_notes','email_evidence'].includes(k)?<textarea required={k==='personalization_notes'&&verified(edit.verification)} value={edit[k]||''} onChange={e=>U({...edit,[k]:e.target.value})}/>:<input required={k==='organization'} type={['email','alternate_email'].includes(k)?'email':['website','evidence_url'].includes(k)?'url':'text'} value={edit[k]||''} onChange={e=>U({...edit,[k]:e.target.value})}/>}</label>)}
    <label>Type<select value={edit.lead_type} onChange={e=>U({...edit,lead_type:e.target.value})}>{['Schools','NGOs'].map(x=><option key={x}>{x}</option>)}</select></label><label>Verification<select value={edit.verification} onChange={e=>U({...edit,verification:e.target.value})}>{verificationStates.map(x=><option key={x}>{x}</option>)}</select></label><label>Lead score<input type="number" min={0} max={100} value={edit.score||0} onChange={e=>U({...edit,score:+e.target.value})}/></label><label>Confidence<input type="number" min={0} max={100} value={edit.confidence||0} onChange={e=>U({...edit,confidence:+e.target.value})}/></label><label>Priority<select value={edit.priority||'Low'} onChange={e=>U({...edit,priority:e.target.value})}>{['Low','Medium','High'].map(x=><option key={x}>{x}</option>)}</select></label></div>
    <label className="check"><input type="checkbox" checked={!!edit.consent} onChange={e=>U({...edit,consent:e.target.checked})}/>Actual outreach consent recorded</label><label className="check"><input type="checkbox" checked={!!edit.do_not_contact} onChange={e=>U({...edit,do_not_contact:e.target.checked})}/>Do not contact</label><button className="primary" disabled={busy}>Save reviewed evidence</button></form><hr/><button disabled={busy} onClick={async()=>{if(await action({op:'suppress',id:modal.r.id})){M(null);N('Do not contact saved. Follow-ups stopped.');}}}>Mark do not contact</button><button disabled={busy||!verified(modal.r.data.verification)} onClick={async()=>{if(await action({op:'personalize',id:modal.r.id})){M(null);N('Personalized preview prepared. Open Preview to review it.');}}}><Mail size={16}/>Generate personalized email</button>
   </>:<><div className="info"><strong>Recipient: {edit.email}</strong><p>{edit.organization} · {edit.verification}</p><p>Brochure: {config.brochure_url||'Not configured'} · Attachments: none (Drive link used)</p><p>Gmail draft ID: {edit.gmail_draft_id||'Not yet created'}</p></div><label>Subject<input value={edit.subject||''} onChange={e=>U({...edit,subject:e.target.value})}/></label><label>Personalized email<textarea rows={16} value={edit.body||''} onChange={e=>U({...edit,body:e.target.value})}/></label><div className="form-actions"><button disabled={busy} onClick={async()=>{if(await action({op:'edit-draft',id:modal.r.id,subject:edit.subject,body:edit.body})){M(null);N('Edited preview saved; approval reset.');}}}>Save edits</button><button disabled={busy||dirty||!data.gmailConnected} onClick={async()=>{if(await action({op:'gmail-draft',id:modal.r.id})){M(null);N('Gmail draft saved. No email was sent.');}}}>Create / update Gmail draft</button>{data.admin&&edit.draft_status==='Draft created'&&<button disabled={busy||dirty} onClick={async()=>{if(await action({op:'approve',id:modal.r.id,previewed:true})){M(null);N('Approved. Sending remains a separate action.');}}}>Approve saved draft</button>}{data.admin&&edit.draft_status==='Approved'&&<button className="primary" disabled={busy||dirty||!edit.consent||edit.do_not_contact||edit.unsubscribed} onClick={async()=>{if(await action({op:'send',id:modal.r.id,previewed:true,confirm_send:true})){M(null);N('Approved email sent through Gmail.');}}}>Send this approved email to {edit.email}</button>}</div><p className="research-footnote">Actions use the saved preview. Save edits before creating or approving a draft. Public email availability is not consent. Automatic reply synchronization is not connected.</p>{edit.draft_status==='Sent'&&<button disabled={busy} onClick={async()=>{if(await action({op:'replied',id:modal.r.id})){M(null);N('Reply recorded; follow-up task stopped.');}}}>Record received reply</button>}</>}</section></div>}
 </div>;
}
