import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
export const runtime = env as unknown as {DB:D1Database;BUCKET:R2Bucket;RESEND_API_KEY?:string;EMAIL_FROM?:string;SUPER_ADMIN_EMAIL?:string;WEBHOOK_SECRET?:string};
export const db = () => {if(!runtime.DB) throw new Error('Database is unavailable. Please try again.'); return runtime.DB;};
export const now = () => new Date().toISOString();
export const id = () => crypto.randomUUID();
export class ApiError extends Error {constructor(message:string, public status=400){super(message);}}
export const fail = (message:string,status=400):never => {throw new ApiError(message,status);};
export async function user(){const u=await getChatGPTUser(); if(!u) return fail('Sign in to continue.',401);return {...u,email:u.email.toLowerCase()};}
export async function access(tenant:string,roles?:string[]){const u=await user();const b=await db().prepare('SELECT * FROM businesses WHERE id=? AND active=1').bind(tenant).first<any>();if(!b) return fail('Workspace not found.',404);const m=await db().prepare('SELECT * FROM members WHERE tenant=? AND email=?').bind(tenant,u.email).first<any>();if(!m || (roles&&!roles.includes(m.role))) return fail('You do not have permission for this action.',403);return {u,m,b,config:JSON.parse(b.config)};}
export function auditStmt(t:string,actor:string,action:string,record:string|null=null){return db().prepare('INSERT INTO audit (id,tenant,actor,action,record,created) VALUES (?,?,?,?,?,?)').bind(id(),t,actor,action,record,now());}
export async function rate(key:string,max=60){const bucket=Math.floor(Date.now()/60000); const row=await db().prepare('INSERT INTO limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key+':'+bucket,bucket+2).first<any>();if(row.count>max)fail('Too many requests. Please wait a minute.',429); if(Math.random()<.01) await db().prepare('DELETE FROM limits WHERE expires<?').bind(bucket).run();}
export function origin(req:Request){const o=req.headers.get('origin');if(o&&o!==new URL(req.url).origin)fail('Cross-origin request blocked.',403);}
export async function readJSON(req:Request,max=1000000){if(Number(req.headers.get('content-length')||0)>max)fail('Request is too large.',413);const reader=req.body?.getReader();if(!reader)fail('Request body required.');let length=0;const chunks:Uint8Array[]=[];while(true){const {value,done}=await reader!.read();if(done)break;length+=value.length;if(length>max){await reader!.cancel();fail('Request is too large.',413);}chunks.push(value);}const bytes=new Uint8Array(length);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length;}try{return JSON.parse(new TextDecoder().decode(bytes));}catch{return fail('Invalid JSON payload.');}}
export const adminRoles=['owner','admin'];
export const writeRoles=['owner','admin','manager','agent'];
export function safeUrl(s:any){if(!s)return '';try{const u=new URL(String(s));if(!['https:','http:'].includes(u.protocol))return fail('Use an HTTP or HTTPS link.');return u.href;}catch{return fail('Enter a valid URL.');}}
export function render(template:string,config:any,lead:any){const vars={...config,lead_name:lead.name,company:lead.company,lead_email:lead.email};return template.replace(/\{\{([a-z_]+)\}\}/g,(_,k)=>Array.isArray(vars[k])?vars[k].join(', '):String(vars[k]??''));}
export async function leadCreate(t:string,d:any,actor:string,c:any){const email=String(d.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail('A valid email is required.');if(!String(d.name||'').trim())fail('A lead name is required.');const existing=await db().prepare('SELECT id FROM records WHERE tenant=? AND kind=? AND email=?').bind(t,'lead',email).first<any>();if(existing)return {id:existing.id,duplicate:true};const rid=id();const data={name:String(d.name).slice(0,200),email,company:String(d.company||'').slice(0,200),phone:String(d.phone||'').slice(0,40),source_url:safeUrl(d.source_url),source_type:String(d.source_type||'manual').slice(0,50),verification:'unverified',stage:c.lead_stages?.[0]||'New',score:Math.min(100,Number(c.scoring_rules?.base||0)+(d.company?Number(c.scoring_rules?.company||0):0)+(d.consent?Number(c.scoring_rules?.consent||0):0)),consent:!!d.consent,consent_at:d.consent?now():null,consent_source:d.consent?String(d.consent_source||d.source_type||'manual'):null,unsubscribed:false,assigned_to:'',next_action:String(d.next_action||(c.follow_up_rules?.length?'Initial follow-up':'')).slice(0,500),next_date:d.next_date||(c.follow_up_rules?.length?new Date(Date.now()+c.follow_up_rules[0]*86400000).toISOString().slice(0,10):''),value:Number(d.value)||0,message:String(d.message||'').slice(0,5000),last_activity:now()};await db().batch([db().prepare('INSERT INTO records (id,tenant,kind,data,email,created,updated) VALUES (?,?,?,?,?,?,?)').bind(rid,t,'lead',JSON.stringify(data),email,now(),now()),auditStmt(t,actor,'Lead created',rid)]);return {id:rid,duplicate:false};}
