import {runtime,db,fail,now} from './crm';
export const integrationEnv=runtime as typeof runtime & {BRAVE_SEARCH_API_KEY?:string;GOOGLE_CLIENT_ID?:string;GOOGLE_CLIENT_SECRET?:string;TOKEN_ENCRYPTION_KEY?:string};
export const gmailConfigured=()=>!!(integrationEnv.GOOGLE_CLIENT_ID&&integrationEnv.GOOGLE_CLIENT_SECRET&&integrationEnv.TOKEN_ENCRYPTION_KEY);
function bytes(s:string){return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
function b64(b:Uint8Array){let s='';for(const v of b)s+=String.fromCharCode(v);return btoa(s);}
async function key(){if(!integrationEnv.TOKEN_ENCRYPTION_KEY)fail('Gmail encryption key is not configured.',409);const raw=bytes(integrationEnv.TOKEN_ENCRYPTION_KEY!);if(raw.length!==32)fail('Gmail encryption key must be 32 bytes.',409);return crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);}
export async function encrypt(value:any){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),new TextEncoder().encode(JSON.stringify(value)));return b64(iv)+'.'+b64(new Uint8Array(data));}
export async function decrypt(value:string){const [iv,data]=value.split('.');return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(iv)},await key(),bytes(data))));}
export async function gmailToken(tenant:string){const row=await db().prepare("SELECT data FROM integrations WHERE tenant=? AND provider='gmail'").bind(tenant).first<any>();if(!row)fail('Connect Gmail for this business first.',409);const saved=await decrypt(row.data);const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:integrationEnv.GOOGLE_CLIENT_ID!,client_secret:integrationEnv.GOOGLE_CLIENT_SECRET!,grant_type:'refresh_token',refresh_token:saved.refresh_token}),signal:AbortSignal.timeout(15000)});if(!response.ok)fail('Gmail authorization expired. Reconnect Gmail.',409);return (await response.json() as any).access_token;}
export async function gmail(tenant:string,path:string,method='GET',body?:any){const token=await gmailToken(tenant);const res=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});if(!res.ok)fail('Gmail could not complete this action. Review connection and retry only after checking Gmail.',502);return res.json() as Promise<any>;}
export function mime(to:string,subject:string,body:string,lead:string){if(/[\r\n]/.test(to)||/[\r\n]/.test(subject))fail('Invalid email headers.');const encoded=b64(new TextEncoder().encode(subject));const raw=`To: ${to}\r\nSubject: =?UTF-8?B?${encoded}?=\r\nX-CRM-Lead-ID: ${lead}\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: base64\r\n\r\n${b64(new TextEncoder().encode(body))}`;return b64(new TextEncoder().encode(raw)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
export async function saveGmail(tenant:string,tokens:any){await db().prepare("INSERT INTO integrations (tenant,provider,data,updated) VALUES (?,'gmail',?,?) ON CONFLICT(tenant,provider) DO UPDATE SET data=excluded.data,updated=excluded.updated").bind(tenant,await encrypt({refresh_token:tokens.refresh_token}),now()).run();}
